[package]
name = "omnis-vanitas"
version = "0.0.0"
edition = "2021"
description = "omnis-vanitas"
license = "Apache-2.0"
keywords = ["frontend"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

